<div class="grid grid-cols-1 md:grid-cols-2 gap-6">
    <div><label class="block mb-2 font-semibold">Project Name</label><input name="name" value="{{ old('name', $project->name) }}" class="w-full rounded-xl border-slate-300" required></div>
    <div><label class="block mb-2 font-semibold">Project Code</label><input name="project_code" value="{{ old('project_code', $project->project_code) }}" class="w-full rounded-xl border-slate-300" required></div>
    <div><label class="block mb-2 font-semibold">Client</label><select name="client_id" class="w-full rounded-xl border-slate-300" required><option value="">Select client</option>@foreach($clients as $client)<option value="{{ $client->id }}" @selected((string) old('client_id', $project->client_id) === (string) $client->id)>{{ $client->name }}</option>@endforeach</select></div>
    <div><label class="block mb-2 font-semibold">Project Manager</label><select name="project_manager_id" class="w-full rounded-xl border-slate-300"><option value="">Select manager</option>@foreach($projectManagers as $manager)<option value="{{ $manager->id }}" @selected((string) old('project_manager_id', $project->project_manager_id) === (string) $manager->id)>{{ $manager->name }}</option>@endforeach</select></div>
    <div><label class="block mb-2 font-semibold">Start Date</label><input type="date" name="start_date" value="{{ old('start_date', $project->start_date?->format('Y-m-d')) }}" class="w-full rounded-xl border-slate-300"></div>
    <div><label class="block mb-2 font-semibold">End Date</label><input type="date" name="end_date" value="{{ old('end_date', $project->end_date?->format('Y-m-d')) }}" class="w-full rounded-xl border-slate-300"></div>
    <div class="md:col-span-2"><label class="block mb-2 font-semibold">Description</label><textarea name="description" rows="4" class="w-full rounded-xl border-slate-300">{{ old('description', $project->description) }}</textarea></div>
    <div class="md:col-span-2"><label class="inline-flex items-center gap-2"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $project->is_active ?? true))><span class="font-semibold">Active</span></label></div>
</div>
