<x-app-layout><x-slot name="header">Website Chat</x-slot><div class="space-y-6">
@if(session('status'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-emerald-800">{{ session('status') }}</div>@endif
<div class="flex items-end justify-between gap-4"><div><h2 class="pg-title">Website Assistant Inbox</h2><p class="pg-subtitle mt-1">All website conversations, AI answers, human contact requests, and unanswered questions.</p></div>@if(auth()->user()?->role?->code==='SUPER_ADMIN')<form method="POST" action="{{ route('admin.website-chat.reset') }}" onsubmit="return confirm('Clear all previous website chat tests?')">@csrf @method('DELETE')<button class="rounded-xl border border-red-300 px-4 py-2 text-sm font-bold text-red-700">Clear previous tests</button></form>@endif</div>
<div class="grid gap-6 xl:grid-cols-2">
<section class="pg-card"><div class="pg-card-body"><h3 class="text-xl font-bold">All Conversations</h3><div class="mt-4 space-y-4">
@forelse($sessions as $session)<article class="rounded-xl border border-slate-200 p-4"><div class="flex justify-between gap-3"><div><strong>{{ $session->name ?? 'Anonymous visitor' }}</strong><div class="text-sm text-slate-500">{{ $session->company }} · {{ $session->email }} · {{ $session->phone }}</div></div><span class="pg-badge">{{ str($session->status)->replace('_',' ')->title() }}</span></div>@if($session->preferred_at)<div class="mt-3 text-sm"><strong>Preferred time:</strong> {{ $session->preferred_at->format('Y-m-d H:i') }}</div>@endif @if($session->contact_notes)<p class="mt-2 text-sm">{{ $session->contact_notes }}</p>@endif<div class="mt-3 space-y-2 rounded-lg bg-slate-50 p-3 text-sm">@foreach($session->messages->reverse() as $message)<div class="{{ $message->role === 'assistant' ? 'border-l-4 border-amber-300 pl-3' : '' }}"><p><strong>{{ ucfirst($message->role) }}:</strong> {{ $message->message }}</p>@if($message->role === 'assistant' && !is_null($message->confidence))<p class="mt-1 text-xs text-slate-400">Confidence: {{ round($message->confidence*100) }}% @if($message->needs_human) · Human review requested @endif</p>@endif</div>@endforeach</div></article>
@empty<p class="text-slate-500">No website conversations yet.</p>@endforelse</div><div class="mt-4">{{ $sessions->links() }}</div></div></section>
<section class="pg-card"><div class="pg-card-body"><h3 class="text-xl font-bold">Knowledge Queue</h3><p class="mt-1 text-sm text-slate-500">Approved answers become available to future conversations.</p><div class="mt-4 space-y-4">
@forelse($knowledge as $item)<form method="POST" action="{{ route('admin.website-chat.knowledge.approve',$item) }}" class="rounded-xl border border-amber-200 bg-amber-50 p-4">@csrf<strong class="block">{{ $item->question }}</strong><div class="mt-2 text-xs font-bold uppercase tracking-wide text-amber-700">AI proposed answer — review before approval</div><textarea name="answer" rows="5" class="mt-2 w-full rounded-xl border-slate-300" placeholder="Write the confirmed PG Integrated answer..." required>{{ old('answer',$item->answer) }}</textarea><button class="pg-btn-primary mt-3">Approve Answer</button></form>
@empty<p class="text-slate-500">No unanswered questions.</p>@endforelse</div></div></section>
</div></div></x-app-layout>
