<x-app-layout><x-slot name="header">Website Chat</x-slot><div class="space-y-6">
@if(session('status'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-emerald-800">{{ session('status') }}</div>@endif
<div><h2 class="pg-title">Website Assistant Inbox</h2><p class="pg-subtitle mt-1">Human contact requests and unanswered questions from the public website.</p></div>
<div class="grid gap-6 xl:grid-cols-2">
<section class="pg-card"><div class="pg-card-body"><h3 class="text-xl font-bold">Contact & Attention Requests</h3><div class="mt-4 space-y-4">
@forelse($sessions as $session)<article class="rounded-xl border border-slate-200 p-4"><div class="flex justify-between gap-3"><div><strong>{{ $session->name ?? 'Anonymous visitor' }}</strong><div class="text-sm text-slate-500">{{ $session->company }} · {{ $session->email }} · {{ $session->phone }}</div></div><span class="pg-badge">{{ str($session->status)->replace('_',' ')->title() }}</span></div>@if($session->preferred_at)<div class="mt-3 text-sm"><strong>Preferred time:</strong> {{ $session->preferred_at->format('Y-m-d H:i') }}</div>@endif @if($session->contact_notes)<p class="mt-2 text-sm">{{ $session->contact_notes }}</p>@endif<div class="mt-3 space-y-2 rounded-lg bg-slate-50 p-3 text-sm">@foreach($session->messages->reverse() as $message)<p><strong>{{ ucfirst($message->role) }}:</strong> {{ str($message->message)->limit(220) }}</p>@endforeach</div></article>
@empty<p class="text-slate-500">No conversations need attention.</p>@endforelse</div><div class="mt-4">{{ $sessions->links() }}</div></div></section>
<section class="pg-card"><div class="pg-card-body"><h3 class="text-xl font-bold">Knowledge Queue</h3><p class="mt-1 text-sm text-slate-500">Approved answers become available to future conversations.</p><div class="mt-4 space-y-4">
@forelse($knowledge as $item)<form method="POST" action="{{ route('admin.website-chat.knowledge.approve',$item) }}" class="rounded-xl border border-amber-200 bg-amber-50 p-4">@csrf<strong class="block">{{ $item->question }}</strong><textarea name="answer" rows="4" class="mt-3 w-full rounded-xl border-slate-300" placeholder="Write the confirmed PG Integrated answer..." required></textarea><button class="pg-btn-primary mt-3">Approve Answer</button></form>
@empty<p class="text-slate-500">No unanswered questions.</p>@endforelse</div></div></section>
</div></div></x-app-layout>
