<x-app-layout><x-slot name="header">Create Outlook Campaign</x-slot>
<div class="mx-auto max-w-6xl space-y-6">
<div><h2 class="pg-title">New Outlook Email Campaign</h2><p class="pg-subtitle mt-1">Create a draft, select approved CRM contacts, then submit it for admin approval.</p></div>
@if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 p-4 text-red-700"><ul>@foreach($errors->all() as $error)<li>• {{ $error }}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{ route('marketing.store') }}" class="space-y-6">@csrf
<section class="pg-card"><div class="pg-card-body"><h3 class="text-lg font-bold">1. Campaign Details</h3><div class="mt-4 grid gap-4 md:grid-cols-2"><div><label class="mb-1 block font-semibold">Campaign Name</label><input name="name" value="{{ old('name') }}" class="w-full rounded-xl border-slate-300" required></div><div><label class="mb-1 block font-semibold">Channel</label><input value="Outlook Email" class="w-full rounded-xl border-slate-300 bg-slate-50" disabled></div><div class="md:col-span-2"><label class="mb-1 block font-semibold">Objective</label><textarea name="objective" rows="3" class="w-full rounded-xl border-slate-300" required>{{ old('objective') }}</textarea></div><div><label class="mb-1 block font-semibold">Country</label><input name="country" value="{{ old('country') }}" class="w-full rounded-xl border-slate-300"></div><div><label class="mb-1 block font-semibold">Industry</label><input name="industry" value="{{ old('industry') }}" class="w-full rounded-xl border-slate-300"></div></div></div></section>
<section class="pg-card"><div class="pg-card-body"><h3 class="text-lg font-bold">2. Audience from CRM</h3><p class="pg-subtitle mt-1">Only contacts with an email address are available.</p><div class="mt-4 grid max-h-80 gap-3 overflow-auto md:grid-cols-2">@forelse($contacts as $contact)<label class="flex items-start gap-3 rounded-xl border border-slate-200 p-3"><input type="checkbox" name="recipient_ids[]" value="{{ $contact->id }}" @checked(in_array($contact->id,old('recipient_ids',[])))><span><strong class="block">{{ $contact->name }}</strong><span class="text-sm text-slate-500">{{ $contact->email }} · {{ $contact->company?->name ?? 'No company' }}</span></span></label>@empty<p class="text-slate-500">No CRM contacts with email addresses. Add contacts in CRM first.</p>@endforelse</div></div></section>
<section class="pg-card"><div class="pg-card-body"><h3 class="text-lg font-bold">3. Email Content</h3><div class="mt-4 space-y-4"><div><label class="mb-1 block font-semibold">Subject</label><input name="email_subject" value="{{ old('email_subject') }}" class="w-full rounded-xl border-slate-300" required></div><div><label class="mb-1 block font-semibold">Message</label><textarea name="message_template" rows="12" class="w-full rounded-xl border-slate-300" required>{{ old('message_template') }}</textarea></div><div><label class="mb-1 block font-semibold">Call-to-action URL</label><input type="url" name="cta_url" value="{{ old('cta_url') }}" class="w-full rounded-xl border-slate-300"></div></div></div></section>
<section class="pg-card"><div class="pg-card-body"><h3 class="text-lg font-bold">4. Proposed Schedule</h3><input type="datetime-local" name="scheduled_at" value="{{ old('scheduled_at') }}" class="mt-4 rounded-xl border-slate-300"><p class="mt-2 text-sm text-slate-500">The campaign remains a draft and will not send at this time.</p></div></section>
<div class="flex justify-end gap-3"><a href="{{ route('marketing.index') }}" class="pg-btn-secondary">Cancel</a><button class="pg-btn-primary">Save Draft</button></div>
</form></div></x-app-layout>
