<x-app-layout><x-slot name="header">Marketing Campaign Review</x-slot>
<div class="space-y-6">
@if(session('status'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-emerald-800">{{ session('status') }}</div>@endif
<div class="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><div class="text-xs font-bold uppercase tracking-widest text-slate-400">Outlook Email Campaign</div><h2 class="pg-title mt-2">{{ $campaign->name }}</h2><p class="pg-subtitle mt-1">{{ $campaign->email_subject }}</p></div><a href="{{ route('marketing.index') }}" class="pg-btn-secondary">Back to Dashboard</a></div>
<div class="grid gap-6 xl:grid-cols-[1.2fr_.8fr]">
<div class="space-y-6"><section class="pg-card"><div class="pg-card-body"><h3 class="text-lg font-bold">Campaign</h3><div class="mt-4 grid gap-4 md:grid-cols-2"><div><div class="pg-stat-label">Status</div><strong>{{ str($campaign->status)->replace('_',' ')->title() }}</strong></div><div><div class="pg-stat-label">Schedule</div><strong>{{ $campaign->scheduled_at?->format('Y-m-d H:i') ?? '-' }}</strong></div><div><div class="pg-stat-label">Country</div><strong>{{ $campaign->country ?? '-' }}</strong></div><div><div class="pg-stat-label">Industry</div><strong>{{ $campaign->industry ?? '-' }}</strong></div><div class="md:col-span-2"><div class="pg-stat-label">Objective</div><p>{{ $campaign->objective }}</p></div></div></div></section>
<section class="pg-card"><div class="pg-card-body"><h3 class="text-lg font-bold">Email Preview</h3><div class="mt-4 rounded-xl border border-slate-200 p-5"><strong class="block border-b pb-3">{{ $campaign->email_subject }}</strong><div class="mt-4 whitespace-pre-wrap text-sm leading-6">{{ $campaign->message_template }}</div>@if($campaign->cta_url)<a href="{{ $campaign->cta_url }}" class="mt-4 inline-block text-blue-700">{{ $campaign->cta_url }}</a>@endif</div></div></section></div>
<div class="space-y-6"><section class="pg-card"><div class="pg-card-body"><h3 class="text-lg font-bold">Approval Control</h3><p class="mt-2 text-sm text-slate-500">Nothing is sent from this page.</p>@if($campaign->status==='draft')<form method="POST" action="{{ route('marketing.request-approval',$campaign) }}" class="mt-4">@csrf<button class="pg-btn-primary w-full justify-center">Submit for Approval</button></form>@elseif($campaign->status==='pending_approval' && auth()->user()?->role?->code==='SUPER_ADMIN')<form method="POST" action="{{ route('marketing.approve',$campaign) }}" class="mt-4">@csrf<button class="pg-btn-primary w-full justify-center">Approve Campaign</button></form>@elseif($campaign->approved_at)<div class="mt-4 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800">Approved by {{ $campaign->approver?->name ?? 'Admin' }} on {{ $campaign->approved_at->format('Y-m-d H:i') }}.</div>@endif</div></section>
<section class="pg-card"><div class="pg-card-body"><h3 class="text-lg font-bold">Recipients ({{ $campaign->recipients->count() }})</h3><div class="mt-4 max-h-[500px] space-y-3 overflow-auto">@foreach($campaign->recipients as $recipient)<div class="rounded-xl border border-slate-200 p-3"><strong class="block">{{ $recipient->contact?->name ?? data_get($recipient->meta,'name') }}</strong><span class="text-sm text-slate-500">{{ $recipient->contact?->email ?? data_get($recipient->meta,'email') }} · {{ $recipient->company?->name ?? data_get($recipient->meta,'company') }}</span></div>@endforeach</div></div></section></div>
</div></div></x-app-layout>
